# **Trabalho Trilha 6 - Coleta e Armazenamento de dados**

In [8]:
import pandas as pd
import numpy as np

mundo_feliz = pd.read_csv('world-happiness-report-2021.csv')

Carga da Tabela contendo Continentes separados por: America, Europa, Asia, Africa e Estados Independentes 
**continentais**

In [9]:
regiao_feliz = pd.read_csv('regional_ID.csv')

regiao_feliz = regiao_feliz.reset_index()
regiao_feliz.drop('index', inplace=True, axis=1)
regiao_feliz.index = regiao_feliz.index + 1
regiao_feliz.index.names = ['Regional_ID']
regiao_feliz.head()

             Regional       Regional indicator
Regional_ID
1                   1  America do Sul e Caribe
2                   2         America do Norte
3                   3                   Europa
4                   4                     Asia
5                   5                   Africa

In [ ]:
liberdade = pd.read_csv('livre.csv')
liberdade.csv.head()

Substituindo a coluna Regional Indicador (arquivo original) pelo valor contendo da tabela regi√£o_feliz (America, Europa, Asia, Africa e Estados Independentes)

In [ ]:
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Latin America and Caribbean', 'Regional_ID'] = '1'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'North America and ANZ', 'Regional_ID'] = '2'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Central and Eastern Europe', 'Regional_ID'] = '3'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Western Europe', 'Regional_ID'] = '3'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'East Asia', 'Regional_ID'] = '4'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Southeast Asia', 'Regional_ID'] = '4'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'South Asia', 'Regional_ID'] = '4'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Sub-Saharan Africa', 'Regional_ID'] = '5'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Middle East and North Africa', 'Regional_ID'] = '5'
mundo_feliz.loc[mundo_feliz['Regional indicator'] == 'Commonwealth of Independent States', 'Regional_ID'] = '6'


#whr_df.drop('Regional indicator', inplace=True, axis=1)
mundo_feliz.index = mundo_feliz.index + 1
mundo_feliz.index.names = ['Pais_ID']

mundo_feliz.to_csv('mundo_feliz_2021.csv')
mundo_feliz.head()

        Country name Regional indicator  ...  Dystopia + residual  Regional_ID
Pais_ID                                  ...
1            Finland     Western Europe  ...                3.253            3
2            Denmark     Western Europe  ...                2.868            3
3        Switzerland     Western Europe  ...                2.839            3
4            Iceland     Western Europe  ...                2.967            3
5        Netherlands     Western Europe  ...                2.798            3

[5 rows x 21 columns]

Livrepara fazer escolhas

In [ ]:
mundo_feliz['livre'] = None

mundo_feliz.loc[mundo_feliz['Explained by: Freedom to make life choices'] < 0.3, 'livre'] =  'Pessimo'
mundo_feliz.loc[(mundo_feliz['Explained by: Freedom to make life choices'] >= 0.3) & (mundo_feliz['Explained by: Freedom to make life choices'] < 0.6), 'livre'] = 'Bom'
mundo_feliz.loc[mundo_feliz['Explained by: Freedom to make life choices'] >= 0.6, 'livre'] =  'Otimo'
mundo_feliz.to_csv('mundo_feliz_2021.csv')
mundo_feliz.head()

mundo_feliz.head()

        Country name Regional indicator  ...  Regional_ID  livre
Pais_ID                                  ...
1            Finland     Western Europe  ...            3  Otimo
2            Denmark     Western Europe  ...            3  Otimo
3        Switzerland     Western Europe  ...            3  Otimo
4            Iceland     Western Europe  ...            3  Otimo
5        Netherlands     Western Europe  ...            3  Otimo

[5 rows x 22 columns]